export const MOCK_PRODUCTS = [
  {
    id: "mock-1",
    name: "Vestido Floral Midi — Zara",
    slug: "vestido-floral-midi-zara",
    shortDescription: "Vestido midi com estampa floral, tecido leve e caimento impecável.",
    description: "Produto em ótimo estado, usado poucas vezes. Sem defeitos.",
    category: "Roupas",
    brand: "Zara",
    sizes: ["M"],
    colors: ["Floral Rosa"],
    condition: "LIKE_NEW",
    originalPrice: 349.90,
    outletPrice: 89.90,
    status: "ACTIVE",
    quantityAvailable: 1,
    images: [{ id: "i1", url: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop", altText: "Vestido floral", color: null }],
    stock: { quantityTotal: 1, quantityReserved: 0, quantitySold: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mock-2",
    name: "Tênis Nike Air Max 270 — Preto",
    slug: "tenis-nike-air-max-270",
    shortDescription: "Tênis Nike original, numeração 38, em perfeito estado.",
    description: "Comprado há 6 meses, usado apenas 3 vezes. Sem marcas de uso.",
    category: "Calçados",
    brand: "Nike",
    sizes: ["38"],
    colors: ["Preto"],
    condition: "LIKE_NEW",
    originalPrice: 899.90,
    outletPrice: 299.90,
    status: "ACTIVE",
    quantityAvailable: 1,
    images: [{ id: "i2", url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop", altText: "Tênis Nike", color: null }],
    stock: { quantityTotal: 1, quantityReserved: 0, quantitySold: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mock-3",
    name: "Bolsa Couro Legítimo — Arezzo",
    slug: "bolsa-couro-arezzo",
    shortDescription: "Bolsa de couro legítimo marrom, compartimento para notebook.",
    description: "Bolsa nova com etiqueta, peça única de exposição.",
    category: "Bolsas",
    brand: "Arezzo",
    sizes: [],
    colors: ["Marrom"],
    condition: "NEW",
    originalPrice: 650.00,
    outletPrice: 219.90,
    status: "ACTIVE",
    quantityAvailable: 1,
    images: [{ id: "i3", url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop", altText: "Bolsa Arezzo", color: null }],
    stock: { quantityTotal: 1, quantityReserved: 0, quantitySold: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mock-4",
    name: "Calça Jeans Slim — Levi's 511",
    slug: "calca-jeans-slim-levis",
    shortDescription: "Calça Levi's 511 tamanho 42, lavagem escura, corte slim.",
    description: "Estado impecável. Comprada nos EUA, poucas vezes usada.",
    category: "Roupas",
    brand: "Levi's",
    sizes: ["42"],
    colors: ["Azul escuro"],
    condition: "LIKE_NEW",
    originalPrice: 499.90,
    outletPrice: 149.90,
    status: "ACTIVE",
    quantityAvailable: 2,
    images: [{ id: "i4", url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop", altText: "Calça jeans", color: null }],
    stock: { quantityTotal: 2, quantityReserved: 0, quantitySold: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mock-5",
    name: "Óculos Ray-Ban Aviador — Dourado",
    slug: "oculos-rayban-aviador",
    shortDescription: "Ray-Ban RB3025 original, armação dourada, lente verde G15.",
    description: "Acompanha case original e nota fiscal.",
    category: "Acessórios",
    brand: "Ray-Ban",
    sizes: [],
    colors: ["Dourado"],
    condition: "NEW",
    originalPrice: 750.00,
    outletPrice: 349.90,
    status: "ACTIVE",
    quantityAvailable: 3,
    images: [{ id: "i5", url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop", altText: "Óculos Ray-Ban", color: null }],
    stock: { quantityTotal: 3, quantityReserved: 0, quantitySold: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mock-6",
    name: "Blusa de Lã Merino — COS",
    slug: "blusa-la-merino-cos",
    shortDescription: "Blusa off-white de lã merino, tamanho P, suave ao toque.",
    description: "Peça única restante da coleção de inverno.",
    category: "Roupas",
    brand: "COS",
    sizes: ["P"],
    colors: ["Off-white"],
    condition: "UNIQUE_PIECE",
    originalPrice: 420.00,
    outletPrice: 119.90,
    status: "ACTIVE",
    quantityAvailable: 1,
    images: [{ id: "i6", url: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=400&fit=crop", altText: "Blusa de lã", color: null }],
    stock: { quantityTotal: 1, quantityReserved: 0, quantitySold: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mock-7",
    name: "Perfume Chanel N°5 — 50ml",
    slug: "perfume-chanel-n5",
    shortDescription: "Perfume original Chanel N°5 EDP 50ml, 80% do frasco.",
    description: "Presente não usado. Caixa original em perfeito estado.",
    category: "Acessórios",
    brand: "Chanel",
    sizes: ["50ml"],
    colors: [],
    condition: "NEW",
    originalPrice: 980.00,
    outletPrice: 480.00,
    status: "ACTIVE",
    quantityAvailable: 1,
    images: [{ id: "i7", url: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&h=400&fit=crop", altText: "Perfume Chanel", color: null }],
    stock: { quantityTotal: 1, quantityReserved: 0, quantitySold: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mock-8",
    name: "Tênis Adidas Ultraboost 22 — Branco",
    slug: "tenis-adidas-ultraboost-22",
    shortDescription: "Adidas Ultraboost 22 numero 41, branco, zero uso.",
    description: "Ganhou de presente mas não usa. Na caixa original.",
    category: "Calçados",
    brand: "Adidas",
    sizes: ["41"],
    colors: ["Branco"],
    condition: "NEW",
    originalPrice: 1199.90,
    outletPrice: 549.90,
    status: "SOLD_OUT",
    quantityAvailable: 0,
    images: [{ id: "i8", url: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=400&fit=crop", altText: "Tênis Adidas", color: null }],
    stock: { quantityTotal: 1, quantityReserved: 0, quantitySold: 1 },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
